### ISSUE TITLE
TypeError: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by swstem-dev** [amazon-ion/ion-js#771]
I'm loading the latest version into an app, and whenever the lib is loaded, i get an error:

```
ion-bundle.min.js:1 Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at Function.value (ion-bundle.min.js:1:4671)
    at Function.value (ion-bundle.min.js:1:4542)
    at 2.@babel/runtime/helpers/classCallCheck (ion-bundle.min.js:1:4821)
    at o (ion-bundle.min.js:1:512)
    at ion-bundle.min.js:1:546
    at 15../BigIntSerde (ion-bundle.min.js:1:47094)
    at o (ion-bundle.min.js:1:512)
    at ion-bundle.min.js:1:546
    at 7../IntSize (ion-bundle.min.js:1:12821)

```

When i load this in my app, while in dev (not a prod build), I don't see the error, and the lib works fine. As soon as its a prod build (minified) or if i include either of the linked cdn files (ion-bundle.js or ion-bundle.min.js) I get the error.

Please see this codepen to reproduce:

https://codepen.io/robcopeland/pen/zYeZpWV/0e6d35137fa8e8299d993d1e4d52a725

**Comment by jobarr-amzn** [comment]
I confirm that I cannot see a repro in that codepen link, and I also looked through the pens accessible from https://codepen.io/robcopeland/ and did not see anything that looked like a reproduction case. Please re-open if you have additional information.

**Comment by wmaillard** [comment]
I'm getting the same error while trying to import [this file](https://amazon-ion.github.io/ion-js/browser/scripts/ion-bundle.min.js) into a tampermonkey script.

### Steps to reproduce

1. Open [the codepen](https://codepen.io/robcopeland/) in Chrome (I'm on 122.0.6261.112)
2. Right click, inspect
3. Look at the **Dev tools console** (not the codepen console)

```
ion-bundle.js:264 Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at Function.calculateSizeThreshold (ion-bundle.js:264:28)
    at Function.calculateSizeThresholds (ion-bundle.js:256:30)
    at 2.@babel/runtime/helpers/classCallCheck (ion-bundle.js:274:43)
    at o (ion-bundle.js:1:628)
    at ion-bundle.js:1:679
    at 15../BigIntSerde (ion-bundle.js:2608:21)
    at o (ion-bundle.js:1:628)
    at ion-bundle.js:1:679
    at 7../IntSize (ion-bundle.js:690:28)
    ```
